services:
  mlops-api-sinerror:
    image: jimenaamr/mlops-api-sinerror #Usa :latest por defecto, no hace falta ponerlo
    container_name: mlops-api-sinerror
    ports:
      - "6000:5000"
    restart: always

  mlops-web-sinerror:
    image: jimenaamr/mlops-web-sinerror
    container_name: mlops-web-sinerror
    ports:
      - "8080:8501"
    environment:
      - API_URL=http://mlops-api-sinerror:5000/predict
    depends_on:
      - mlops-api-sinerror
    restart: always
